AmbSignalMapper: Fix compile time error
Generated c++ codes by json2amb use 'auto' keyword. However, Generated
CMakeLists.txt has '-std=gnu++0x' option. Because of this reason, below
errors occur.

---------------------------------------
error: use of ‘auto’ in lambda parameter declaration only available with
-std=c++14 or -std=gnu++14
---------------------------------------

This patch fixes the bug by using '-std=c++14' instead of
'-std=gnu++0x'

Signed-off-by: Sangjung Woo <sangjung.woo@samsung.com>